name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
  - type: input
    attributes:
      label: Environment
      description: OS, Expo SDK version, Device/Simulator
  - type: textarea
    attributes:
      label: Additional context
