name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
  - type: textarea
    attributes:
      label: Additional context
